on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: 'Install dependencies'
      run: yarn install --frozen-lockfile 
    - name: 'Build'
      run: yarn build-storybook
    - name: 'upload'
      uses: actions/upload-pages-artifact@v3
      with:
        path: storybook-static # change to your build folder
    - name: 'Deploy to GitHub Pages'
      uses:  actions/deploy-pages@v4
      with:
        token: ${{ github.token }}

